### 1.数据库风格的DataFrame连接

In [2]:
import pandas as pd
import numpy as np

In [7]:
df1 = pd.DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1':range(7)})
df2 = pd.DataFrame({'key':['a','b','d'], 'data2':range(3)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [8]:
df2

key  data2
0   a      0
1   b      1
2   d      2

**通过merge方法对俩个DataFrame对象进行联合，如果没有指定列名，将自动将重叠列明作为连接的键**

**默认做内连接，会自动舍弃没有交集的数据**

In [9]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [11]:
pd.merge(df1,df2,on = 'key') # 显示指定要连接的列

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

**如果每个对象的列名是不同的，你可以分别为他们指定列明**

In [12]:
df3 = pd.DataFrame({'key1':['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1':range(7)})
df4 = pd.DataFrame({'key2':['a','b','d'], 'data2':range(3)})

In [13]:
df3

key1  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [14]:
df4

key2  data2
0    a      0
1    b      1
2    d      2

In [15]:
pd.merge(df3,df4,left_on = 'key1',right_on = 'key2')

key1  data1 key2  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

**通过参数how设置连接方式**

In [ ]:
pd.merge(df1,df2,how = 'outer')

**使用多个键进行合并时，传入一个列名的列表**

In [3]:
left = pd.DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1, 2, 3]})
right = pd.DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'rval':[4, 5, 6, 7]})

In [4]:
pd.merge(left, right, on = ['key1','key2'], how = 'outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

**当对数据进行合并后，有重复的列名，我们可以通过suffixes为重叠的列名指定要添加的字符串**

In [5]:
pd.merge(left,right,on = 'key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [6]:
pd.merge(left,right,on = 'key1',suffixes = ('_left', 'right'))

key1 key2_left  lval key2right  rval
0  foo       one     1       one     4
1  foo       one     1       one     5
2  foo       two     2       one     4
3  foo       two     2       one     5
4  bar       one     3       one     6
5  bar       one     3       two     7

## 2.根据索引合并

**当我们需要将索引进行合并时，可以使用left_index和right_index来表示索引作为合并的键**

In [7]:
left = pd.DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})
right = pd.DataFrame({'group_val':[3.5,7]},index = ['a','b'])


In [8]:
left

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [9]:
right

group_val
a        3.5
b        7.0

In [10]:
pd.merge(left,right,left_on = 'key',right_index = True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

**用俩边的索引进行合并**

In [12]:
left1 = pd.DataFrame([[1,2],[3,4],[5,6]], index = ['a', 'c', 'e'],columns = ['Ohio','Nevada'])
left1

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [13]:
right1 = pd.DataFrame([[7, 8],[9, 10],[11, 12],[13, 14]],index = ['b','c','d','e'],columns = ['Missouri','Alabama'])
right1

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [17]:
pd.merge(left1,right1,left_index = True,right_index = True,how = 'outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

**可以使用join方法实现键的左连接**

In [19]:
left1.join(right1,how = 'outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

**join方法还可以实现多个dataframe对象的合并**

In [20]:
another = pd.DataFrame([[7, 8],[9, 10],[11, 12],[16, 17]],index = ['a','c','e','f'],columns = ['New York','Oregon'])
another

New York  Oregon
a         7       8
c         9      10
e        11      12
f        16      17

In [22]:
left1.join([right1,another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

## 3.沿轴向连接

**concatenate用于数据的拼接、绑定或堆叠**

In [23]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.concatenate([arr,arr],axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

**concat方法可用于处理多个索引都不出现重叠的情况**

In [43]:
s1 = pd.Series([0,1],index = ['a','b'])
s2 = pd.Series([2, 3, 4], index = ['c','d','e'])
s3 = pd.Series([5,6],index = ['f','g'])
s1

a    0
b    1
dtype: int64

In [41]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [42]:
pd.concat([s1,s2,s3],axis = 1)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

**为区分连接后的数据属于哪一部分，可用key关键字实现一个多层索引**

In [47]:
result = pd.concat([s1,s1,s3],keys = ['one','two','three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [48]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

**将相同的逻辑用到DataFrame对象中**

In [51]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2),index = ['a','b','c'],columns = ['one','two'])
df2 = pd.DataFrame(np.arange(4).reshape(2,2),index = ['a','c'],columns = ['three','four'])

In [52]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [53]:
df2

three  four
a      0     1
c      2     3

In [55]:
pd.concat([df1,df2],axis = 1,keys = ['level1','level2'])

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    0.0  1.0
b      2   3    NaN  NaN
c      4   5    2.0  3.0

**通过names参数设置轴级名称**

In [56]:
pd.concat([df1,df2],axis = 1,keys = ['level1','level2'],names = ['upper','lower'])

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


upper level1     level2     
lower    one two  three four
a          0   1    0.0  1.0
b          2   3    NaN  NaN
c          4   5    2.0  3.0

**通过设置参数ignore_index = True,使联合后的行索引不包含之前的任何相关数据**

In [57]:
pd.concat([df1,df2],ignore_index = True)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


four  one  three  two
0   NaN  0.0    NaN  1.0
1   NaN  2.0    NaN  3.0
2   NaN  4.0    NaN  5.0
3   1.0  NaN    0.0  NaN
4   3.0  NaN    2.0  NaN

## 4.联合重叠数据

**考虑到数据联合场景，即不是合并操作，也不是连接操作，如numpy中的where函数，等价于if-else操作**

In [58]:
a = pd.Series([np.nan,2.5,0.,3.5,4.5,np.nan],index = ['f','e','d','c','b','a'])
b = pd.Series([0.,np.nan,2,np.nan,np.nan,5.],index = ['a','b','c','d','e','f'])

In [59]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [60]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [62]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

**Series有一个combine_first的方法，该方法可实现上述操作：根据你传入的对象来'修补'调用对象的缺失值**

In [63]:
b.combine_first(a)

a    0.0
b    4.5
c    2.0
d    0.0
e    2.5
f    5.0
dtype: float64