## 一.过滤缺失值

1.使用isnull来判断当前值是否为缺失值

In [23]:
import pandas as pd
import numpy as np
data = pd.Series(['a', 'b', np.nan, 'd'])
data

0      a
1      b
2    NaN
3      d
dtype: object

In [24]:
data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

过滤缺失值

In [25]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna() # 等价于data[data.notnull]

0    1.0
2    3.5
4    7.0
dtype: float64

对于dataframe对象时，默认删除包含缺失值的行

In [26]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [27]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

设置参数how = 'all'，将删除所有值均为‘NA’的行

In [28]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

设置axis = 1，删除包含缺失值的列

In [29]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [30]:
data.dropna(axis = 1, how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

## 二.补全缺失值

使用fillna方法对缺失值补全

In [31]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [32]:
data.fillna(0)

0    1    2    4
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  6.5  3.0  0.0

使用字典，对不同的列设定不同的填充值

In [33]:
data.fillna({0:0.5,1:1.5,2:2.5,4:3.5})

0    1    2    4
0  1.0  6.5  3.0  3.5
1  1.0  1.5  2.5  3.5
2  0.5  1.5  2.5  3.5
3  0.5  6.5  3.0  3.5

In [34]:
# 设置inplace参数为True，修改当前对象
data.fillna(0, inplace = True)
data

0    1    2    4
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  6.5  3.0  0.0

## 三.数据转换

### 1.删除重复值

In [35]:
data = pd.DataFrame({'k1':['one', 'two'] * 3 + ['two'],'k2':[1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

duplicated方法用于检查是否出现重复行(与之前出现过的行相同)

In [36]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

使用drop_duplicates方法返回内容为False的部分,默认对列进行操作

In [37]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [38]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

根据指定列判断数据是否重复，设置参数keep为last保留最后一个数

In [39]:
data.drop_duplicates(['k1','k2'],keep = 'last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 2.使用函数或映射进行数据转换

In [43]:
k1_to_v1 = {'one':'a','two':'b'}
data['v1'] = data['k1'].map(k1_to_v1)
data

k1  k2 v1
0  one   1  a
1  two   1  b
2  one   2  a
3  two   3  b
4  one   3  a
5  two   4  b
6  two   4  b

In [18]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
                    'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

判断这些食物的动物肉类型

In [5]:
meat_to_animal = {'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

使用str.lower方法，将字母转化为小写

In [7]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [9]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

也可以传入一个函数

In [13]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 3.替代值

In [21]:
data = pd.Series([1.0,-999,2,-999,-1000,3])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

使用replace方法替换掉指定的数据

In [22]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

如果要替换多个值，可传入一个列表

In [23]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

将不同的值替换为不同的值，可传入替换值的列表

In [24]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 4.重命名轴索引

轴索引也有map方法，可以传入函数

In [44]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [45]:
transform = lambda x: x[:4].upper()

In [46]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [47]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

使用rename方法，修改索引内容

In [48]:
data.rename(index = str.title, columns = str.upper,inplace = True)
data

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

rename还可以与字典结合

In [49]:
data.rename(index = {'Ohio':'INDIANA'},columns = {'three':'peekaboo'},inplace = True)
data

ONE  TWO  THREE  FOUR
INDIANA    0    1      2     3
Colo       4    5      6     7
New        8    9     10    11

### 5.离散化和分箱

将各个阶段的年龄进行分组，可以使用过pandas中的cut方法

In [43]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

cats = pd.cut(ages,bins)
cats  # 将各个年龄进行分段 左开又闭

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

codes属性可以得到年龄的数据标签

In [44]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

使用categories方法，得到各个分段

In [45]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

得到各个分段的数据个数

In [42]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

通过设置参数right = False来改变那一边是封闭的

In [46]:
pd.cut(ages,bins,right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

可以通过labels参数传递一个列表自定义箱名

In [47]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels = group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

传入整数，cut会将数据计算成等长的箱

In [48]:
pd.cut(np.random.rand(20),4)

[(0.755, 0.988], (0.522, 0.755], (0.522, 0.755], (0.0539, 0.288], (0.522, 0.755], ..., (0.288, 0.522], (0.0539, 0.288], (0.755, 0.988], (0.288, 0.522], (0.522, 0.755]]
Length: 20
Categories (4, interval[float64]): [(0.0539, 0.288] < (0.288, 0.522] < (0.522, 0.755] < (0.755, 0.988]]

qcut，根据样本的分布进行分箱

In [52]:
data = np.random.rand(1000)
cats = pd.qcut(data,4)
cats

[(0.265, 0.507], (-0.000888, 0.265], (0.265, 0.507], (-0.000888, 0.265], (0.757, 1.0], ..., (0.757, 1.0], (-0.000888, 0.265], (-0.000888, 0.265], (0.265, 0.507], (-0.000888, 0.265]]
Length: 1000
Categories (4, interval[float64]): [(-0.000888, 0.265] < (0.265, 0.507] < (0.507, 0.757] < (0.757, 1.0]]

In [55]:
pd.value_counts(cats)

(0.757, 1.0]          250
(0.507, 0.757]        250
(0.265, 0.507]        250
(-0.000888, 0.265]    250
dtype: int64

### 6.检查和过滤异常值

In [58]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.017070    -0.022765    -0.049881     0.044523
std       1.020768     1.011687     1.002969     0.979977
min      -2.819045    -2.872920    -3.148765    -4.024323
25%      -0.737167    -0.728822    -0.670958    -0.589675
50%      -0.040663    -0.016368    -0.055359     0.028124
75%       0.642810     0.650827     0.611148     0.608448
max       3.498539     2.873571     3.517527     3.232937

找出一列中绝对值大于三的值

In [59]:
col = data[2]
col[np.abs(col) > 3]

177   -3.040915
200   -3.148765
412    3.517527
Name: 2, dtype: float64

对布尔值的dataframe对象使用any方法，找出所有绝对值大于3的数

In [62]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
37   0.078611  0.433023  1.229645  3.147901
177 -0.885386 -0.268459 -3.040915  0.017750
185 -0.132178  0.432316 -0.849699  3.035311
200  0.046878  2.693831 -3.148765 -0.352068
222  3.498539  0.716820  0.587570 -0.962762
223  3.125800 -0.586463 -0.057788  0.535734
262  3.273763  0.407611 -2.632824  0.460921
412 -1.091662 -0.202037  3.517527 -1.543533
608 -0.021534 -1.846445 -0.487949  3.030137
762  3.254976  1.528176  0.182733  0.032624
827 -1.472889 -0.860872 -0.459335 -4.024323
964 -1.136628  1.538128 -1.358200  3.232937

### 7.置换和随机抽样

使用numpy.random.permutation对dataframe中的Series或行进行置换

In [68]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [71]:
sampler = np.random.permutation(5)
sampler

array([0, 1, 4, 2, 3])

In [72]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15

使用sample方法随机抽取不重复的子集

In [74]:
df.sample(n = 3)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11

通过设置参数replace = True，允许有重复值

In [75]:
df.sample(n = 10, replace = True)

0   1   2   3
3  12  13  14  15
3  12  13  14  15
0   0   1   2   3
3  12  13  14  15
4  16  17  18  19
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3

### 8.计算指标/虚拟变量

在dataframe中的一列有k个不同得到值，可以通过getdummies方法衍生一个k列的值为1或0的矩阵

In [50]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'], 'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [51]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

通过设置参数prefix为每一列上的变量设置前缀

In [78]:
dummies = pd.get_dummies(df['key'],prefix = 'key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

将get_dummies与cut等离散化函数结合使用是统计应用的一个有用方法

In [79]:
values = np.random.rand(10)
values

array([0.60390228, 0.9819237 , 0.41250062, 0.6560741 , 0.09503322,
       0.52106739, 0.51267744, 0.65027185, 0.0959226 , 0.96303767])

In [81]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           0           0           1           0           0
3           0           0           0           1           0
4           1           0           0           0           0
5           0           0           1           0           0
6           0           0           1           0           0
7           0           0           0           1           0
8           1           0           0           0           0
9           0           0           0           0           1